# Environment
PLATFORM_ENV=local

# Docker Compose
COMPOSE_FILE=docker-compose.yml

# URLs
JENKINS_URL=http://localhost:8080
NEXUS_URL=http://localhost:8081
SONAR_URL=http://localhost:9000
TOMCAT_URL=http://localhost:9090
