#!/usr/bin/env bash

#
# Service Registry
#
# Format:
# Display Name | Docker Compose Service | URL
#

SERVICES=(

    "Jenkins|jenkins|http://localhost:8080|true"

    "Nexus|nexus|http://localhost:8081|true"

    "SonarQube|sonarqube|http://localhost:9000|true"

    "Tomcat|tomcat|http://localhost:9090|true"

)
